# Generated by Django 4.2.13 on 2024-06-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAddress',
        ),
    ]
